title: CloudPath Academy
description: Your guide to AWS certification success
url: "https://www.cloudpathacademy.com"

theme: jekyll-theme-slate

# Build settings
markdown: kramdown
highlighter: rouge

# Exclude from build
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - dnstodo.md
